const data = [
    {
      id: 1,
      title: 'buttermilk pancakes',
      category: 'breakfast',
      price: 15.99,
      img: './images/item-1.jpeg',
      desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel quam nec turpis volutpat iaculis vel et nunc.`,
    },
    {
      id: 2,
      title: 'diner double',
      category: 'lunch',
      price: 13.99,
      img: './images/item-2.jpeg',
      desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel quam nec turpis volutpat iaculis vel et nunc`,
    },
    {
      id: 3,
      title: 'godzilla milkshake',
      category: 'shakes',
      price: 6.99,
      img: './images/item-3.jpeg',
      desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel quam nec turpis volutpat iaculis vel et nunc`,
    },
    {
      id: 4,
      title: 'country delight',
      category: 'breakfast',
      price: 20.99,
      img: './images/item-4.jpeg',
      desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel quam nec turpis volutpat iaculis vel et nunc`,
    },
    {
      id: 5,
      title: 'egg attack',
      category: 'lunch',
      price: 22.99,
      img: './images/item-5.jpeg',
      desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel quam nec turpis volutpat iaculis vel et nunc`,
    },
    {
      id: 6,
      title: 'oreo dream',
      category: 'shakes',
      price: 18.99,
      img: './images/item-6.jpeg',
      desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel quam nec turpis volutpat iaculis vel et nunc`,
    },
    {
      id: 7,
      title: 'bacon overflow',
      category: 'breakfast',
      price: 8.99,
      img: './images/item-7.jpeg',
      desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel quam nec turpis volutpat iaculis vel et nunc`,
    },
    {
      id: 8,
      title: 'american classic',
      category: 'lunch',
      price: 12.99,
      img: './images/item-8.jpeg',
      desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel quam nec turpis volutpat iaculis vel et nunc`,
    },
    {
      id: 9,
      title: 'quarantine buddy',
      category: 'shakes',
      price: 16.99,
      img: './images/item-9.jpeg',
      desc: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel quam nec turpis volutpat iaculis vel et nunc`,
    },
  ];
  export default data;